include $(BASEDIR)/Rules.mk

subdir-y += secure_storage_test
subdir-y += embUnit
subdir-y += crypto_test
subdir-y += example

include $(BASEDIR)/Post.mk

# Object file contains changeset and compiler information.
#kernel.o: $(BASEDIR)/include/xen/compile.h
